[workspace]
members = [
    "day-*",
    "day-01",
]
resolver = "2"

[workspace.dependencies]
fancy-regex = "0.14.0"
nom = "7.1.3"
regex = "1.11.1"
rstest = "0.23.0"
tracing = "0.1.41"

[workspace.dependencies.test-log]
version = "0.2.16"
features = ["trace"]
default-features = false
