create day:
    cargo generate --path ./daily-template --name {{day}}

run day part:
    cargo run -r -p {{day}} --bin {{part}}

test day:
    RUST_LOG=trace cargo watch -x "nextest run -p {{day}} --no-capture"

bench day:
    cargo bench -p "{{day}}"

lint:
    cargo watch -x "clippy --all-targets --all-features"

